import os
from datetime import datetime
from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        pass  # No default header

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, "Generated by NZ Property Settlement", align="C")

def generate_pdf(property_address, yearly_rates, local_council, regional_council, settlement_date, purchase_price, gst_applicable, adjustments,
                 local_vendor_days, local_vendor_amount, local_purchaser_days, local_purchaser_amount,
                 regional_vendor_days, regional_vendor_amount, regional_purchaser_days, regional_purchaser_amount,
                 client_name="Mike Ross", client_care_of="c/o Spekter Litt", client_address="147 Pioneer Street, Tauranga", deposit_amount=None,
                 matter_reference=None, today_date=None):

    pdf = PDF()
    pdf.set_auto_page_break(auto=True, margin=15)

    ## PAGE 1 ##
    pdf.add_page()

    # Insert logo
    logo_path = os.path.join(os.path.dirname(__file__), "logo.png")
    if os.path.exists(logo_path):
        pdf.image(logo_path, x=10, y=8, w=30)
        pdf.ln(20)

    # Date (left aligned)
    if not today_date:
        today_date = datetime.now().strftime("%d %B %Y")
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, today_date, ln=True, align="L")  # Left-aligned date
    pdf.ln(5)

    # Client Info with reduced spacing
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 6, client_name, ln=True)
    pdf.cell(0, 6, client_care_of, ln=True)
    pdf.cell(0, 6, client_address, ln=True)

    # Matter Reference
    if matter_reference:
        pdf.ln(5)
        pdf.set_font("Arial", 'I', 11)
        pdf.cell(0, 10, f"Matter Reference: {matter_reference}", ln=True)

    pdf.ln(10)

    # Title and Subtitle
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, f"Settlement Statement as at {today_date}", ln=True, align="C")
    pdf.ln(10)

    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, f"Re: Sale and Purchase of {property_address}", ln=True, align="C")
    pdf.ln(10)

    # Financial Table
    col_widths = [100, 45, 45]
    line_height = 8
    border_style = 'B'  # Bottom-only borders

    pdf.set_fill_color(220, 220, 220)
    pdf.set_font("Arial", 'B', 12)
    pdf.cell(col_widths[0], 10, "Details", border=1, fill=True)
    pdf.cell(col_widths[1], 10, "Debit", border=1, align='C', fill=True)
    pdf.cell(col_widths[2], 10, "Credit", border=1, align='C', fill=True, ln=True)
    pdf.set_font("Arial", size=12)

    def add_row(label, debit=None, credit=None, is_total=False):
        x_start = pdf.get_x()
        y_start = pdf.get_y()

        if is_total:
            pdf.set_font("Arial", 'B', 12)
            fill = True
        else:
            pdf.set_font("Arial", size=12)
            fill = False

        pdf.multi_cell(col_widths[0], line_height, label, border=border_style, fill=fill)
        y_end = pdf.get_y()
        row_height = y_end - y_start

        pdf.set_xy(x_start + col_widths[0], y_start)

        if debit is not None:
            pdf.cell(col_widths[1], row_height, f"{debit:,.2f}", border=border_style, align='C', fill=fill)
        else:
            pdf.cell(col_widths[1], row_height, "", border=border_style, fill=fill)

        if credit is not None:
            pdf.cell(col_widths[2], row_height, f"{credit:,.2f}", border=border_style, align='C', fill=fill, ln=True)
        else:
            pdf.cell(col_widths[2], row_height, "", border=border_style, fill=fill, ln=True)

    # Add Table Rows
    add_row("Purchase Price", credit=purchase_price)

    if deposit_amount:
        add_row("Deposit", credit=deposit_amount)

    gst_amount = 0
    if gst_applicable:
        gst_amount = purchase_price * 0.15
        add_row("Plus: GST", debit=gst_amount)

    add_row(f"Local Council Rates Adjustment ({local_council})", debit=local_purchaser_amount)
    add_row(f"Regional Council Rates Adjustment ({regional_council})", debit=regional_purchaser_amount)

    total_debits = gst_amount + local_purchaser_amount + regional_purchaser_amount
    total_credits = purchase_price + (deposit_amount if deposit_amount else 0)
    total_due = total_debits + total_credits

    add_row("Total Amount Payable", debit=total_due, is_total=True)

    pdf.ln(20)

    # Signature Block
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 10, "Yours faithfully,", ln=True)
    pdf.ln(10)
    pdf.cell(0, 10, "Hollier & Associates", ln=True)

    ## PAGE 2 ##
    pdf.add_page()

    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "Apportionment Details", ln=True, align="C")
    pdf.ln(10)

    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, f"Sale and Purchase of: {property_address}", ln=True)
    pdf.cell(0, 10, f"Settlement Date: {settlement_date.strftime('%d %b %Y')}", ln=True)
    pdf.ln(10)

    def add_council_table(title, vendor_days, vendor_amount, purchaser_days, purchaser_amount):
        pdf.set_font("Arial", 'B', 12)
        pdf.cell(0, 10, title, ln=True)
        pdf.set_font("Arial", 'B', 11)
        pdf.set_fill_color(220, 220, 220)
        pdf.cell(50, 10, "Party", border=1, fill=True)
        pdf.cell(50, 10, "Days", border=1, align='C', fill=True)
        pdf.cell(50, 10, "Amount", border=1, align='C', fill=True, ln=True)

        pdf.set_font("Arial", size=11)
        pdf.cell(50, 10, "Vendor", border=1)
        pdf.cell(50, 10, str(vendor_days), border=1, align='C')
        pdf.cell(50, 10, f"{vendor_amount:,.2f}", border=1, align='C', ln=True)

        pdf.cell(50, 10, "Purchaser", border=1)
        pdf.cell(50, 10, str(purchaser_days), border=1, align='C')
        pdf.cell(50, 10, f"{purchaser_amount:,.2f}", border=1, align='C', ln=True)

        total_days = vendor_days + purchaser_days
        total_amount = vendor_amount + purchaser_amount

        pdf.set_font("Arial", 'B', 11)
        pdf.cell(50, 10, "Total", border=1, fill=True)
        pdf.cell(50, 10, str(total_days), border=1, align='C', fill=True)
        pdf.cell(50, 10, f"{total_amount:,.2f}", border=1, align='C', fill=True, ln=True)
        pdf.ln(10)

    add_council_table(f"Local Council Rates ({local_council})", local_vendor_days, local_vendor_amount, local_purchaser_days, local_purchaser_amount)
    add_council_table(f"Regional Council Rates ({regional_council})", regional_vendor_days, regional_vendor_amount, regional_purchaser_days, regional_purchaser_amount)

    pdf_output = pdf.output(dest='S').encode('latin1')
    return pdf_output
