import os
from datetime import datetime
from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        pass  # No default header

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, "Generated by NZ Property Settlement", align="C")

def generate_pdf(
    property_address, 
    purchase_price, 
    client_name, 
    client_address, 
    local_yearly_rates, 
    regional_yearly_rates, 
    local_council, 
    regional_council, 
    local_purchaser_days, 
    regional_purchaser_days, 
    local_purchaser_amount, 
    regional_purchaser_amount, 
    local_vendor_days, 
    regional_vendor_days, 
    local_vendor_amount, 
    regional_vendor_amount, 
    settlement_date, 
    deposit=None, 
    ):
    
    # Initialize the PDF object
    pdf = PDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # PAGE 1
    pdf.add_page()

    # Insert logo (if available)
    logo_path = os.path.join(os.path.dirname(__file__), "logo.png")
    if os.path.exists(logo_path):
        pdf.image(logo_path, x=10, y=8, w=30)
        pdf.ln(20)

    # Date (left aligned)
    today_date = datetime.now().strftime("%d %B %Y")
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, today_date, ln=True, align="L")  # Left-aligned date
    pdf.ln(5)

    # Client Info (reduced spacing)
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 6, client_name, ln=True)
    pdf.cell(0, 6, client_address, ln=True)
    pdf.ln(10)

    # Title and Subtitle
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, f"Settlement Statement as at {settlement_date.strftime('%d %B %Y')}", ln=True, align="C")
    pdf.ln(10)

    pdf.set_font("Arial", 'B', 12)
    pdf.cell(0, 10, f"Re: {property_address}", ln=True, align="L")
    pdf.ln(10)

    # Simple Financial Table (Description and Amount columns)
    col_widths = [120, 50]  # Width for "Description" and "Amount" columns
    line_height = 8
    border_style = 'B'  # Bottom-only borders

    pdf.set_font("Arial", size=12)

    def add_row(description, amount=None, bold=False):
        """Adds a row to the financial table."""
        x_start = pdf.get_x()
        y_start = pdf.get_y()

        pdf.set_font("Arial", size=12, style='B' if bold else '')

        # Column 1: Description
        pdf.multi_cell(col_widths[0], line_height, description, border=border_style)
        y_end = pdf.get_y()
        row_height = y_end - y_start

        pdf.set_xy(x_start + col_widths[0], y_start)

        # Column 2: Amount
        if amount is not None:
            pdf.cell(col_widths[1], row_height, f"{amount:,.2f}", border=border_style, align='R')  # Right-aligned

        pdf.ln(row_height)

    # Add Table Rows (the required entries)
    add_row("Purchase Price", amount=purchase_price)

    add_row(f"{local_council} Rates: {local_purchaser_days} days", amount=local_purchaser_amount)
    add_row(f"{regional_council} Rates: {regional_purchaser_days} days", amount=regional_purchaser_amount)
    
    if deposit:
        add_row("Less Deposit Paid", amount=deposit)

    # Always include the "Balance required to settle"
    add_row("Balance required to settle", amount=purchase_price - (deposit or 0), bold=True)

    # Signature Block
    pdf.ln(20)
    pdf.set_font("Arial", '', 12)
    pdf.cell(0, 10, "Yours faithfully,", ln=True)
    pdf.ln(10)
    pdf.cell(0, 10, "Hollier & Associates", ln=True)

    # Add a second page for working on council rates
    pdf.add_page()
    
    # Title for the second page
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(0, 10, "Calculation of Apportionments", ln=True, align="C")
    pdf.ln(10)

    # Add breakdown of the calculations for purchaser and vendor portions
    pdf.set_font("Arial", size=12)
    pdf.multi_cell(0, 8, f"{local_council} Rates Calculation @ ${local_yearly_rates} / year:\n\n"
                         f"Purchaser: ${local_purchaser_amount} | Days: {local_purchaser_days}\n"
                         f"Vendor: ${local_vendor_amount} | Days: {local_vendor_days}\n\n"
                         f"{regional_council} Rates Calculation @ ${regional_yearly_rates} / year:\n\n"
                         f"Purchaser: ${regional_purchaser_amount} | Days: {regional_purchaser_days}\n"
                         f"Vendor: ${regional_vendor_amount} | Days: {regional_vendor_days}\n")

    # Output the PDF
    pdf_output = pdf.output(dest='S').encode('latin1')
    return pdf_output
