from docx import Document
from io import BytesIO
from docx.shared import Inches
from datetime import datetime

def generate_docx(data: dict) -> bytes:
    doc = Document()

    # Add logo to the top left corner
    if 'logo_path' in data and data['logo_path']:
        # Insert logo at the top left of the document (adjust size as needed)
        header = doc.sections[0].header
        paragraph = header.paragraphs[0]
        run = paragraph.add_run()
        run.add_picture(data['logo_path'], width=Inches(1.5))  # Adjust width as needed
        paragraph.alignment = 0  # Align to left

    # Header: Title and date
    doc.add_paragraph()
    doc.add_paragraph(datetime.now().strftime("%d %B %Y"))
    doc.add_paragraph()

    doc.add_paragraph(f"{data['client_name']}")
    doc.add_paragraph(f"{data['client_address']}")
    doc.add_paragraph(f"By email: {data['client_email']}")
    doc.add_paragraph()  # Blank line for spacing
# Blank line for spacing

    # Table: Financials (Debits and Credits)
    doc.add_heading('Statement of Account', level=1)
    doc.add_paragraph(f"RE: {data['property_address']}")

    # Table structure: Description, Amount
    table = doc.add_table(rows=1, cols=2)
    table.style = 'Table Grid'

    # Table headers
    hdr_cells = table.rows[0].cells
    hdr_cells[0].text = 'Description'
    hdr_cells[1].text = 'Amount (NZD)'

    def add_row_to_table(description, amount=None):
        row_cells = table.add_row().cells
        row_cells[0].text = description
        if amount is not None:
            row_cells[1].text = f"{amount:,.2f}"

    # Add the working rows:
    add_row_to_table("DEBIT: Purchase Price", amount=data['purchase_price'])

    # Rates: Local and Regional Council rates (if installment paid, debit; otherwise, credit)
    if data['local_installment_paid']:
        add_row_to_table(f"DEBIT: {data['local_council']} Rates: {data['local_purchaser_days']} days", amount=data['local_purchaser_amount'])
    else:
        add_row_to_table(f"CREDIT: {data['local_council']} Rates: {data['local_vendor_days']} days", amount=data['local_vendor_amount'])

    if data['regional_installment_paid']:
        add_row_to_table(f"DEBIT: {data['regional_council']} Rates: {data['regional_purchaser_days']} days", amount=data['regional_purchaser_amount'])
    else:
        add_row_to_table(f"CREDIT: {data['regional_council']} Rates: {data['regional_vendor_days']} days", amount=data['regional_vendor_amount'])

    # Deposit
    if data['deposit']:
        add_row_to_table("CREDIT: Less Deposit Paid", amount=data['deposit'])

    # Final Balance Required
    final_balance = data['purchase_price'] - (data['deposit'] or 0)
    add_row_to_table("Balance required to settle", amount=final_balance)

    # Summary
    doc.add_paragraph(f"\nTotal balance required to settle: NZD {final_balance:,.2f}")
    doc.add_paragraph()  # Blank line for spacing

    # Signature Block
    doc.add_paragraph("Yours faithfully,")
    doc.add_paragraph("Hollier & Associates")

    # Add footer with custom text
    footer = doc.sections[0].footer
    footer_paragraph = footer.paragraphs[0]
    footer_paragraph.text = "Generated by Hollier & Associates | www.hollierassociates.com"
    footer_paragraph.alignment = 1  # Center the footer text

    # Second Page: Apportionments Calculation Breakdown
    doc.add_page_break()
    
    doc.add_paragraph()
    doc.add_heading('Calculation of Apportionments', level=1)

    # Local Council Breakdown
    doc.add_paragraph(f"{data['local_council']} Rates Calculation @ ${data['local_yearly_rates']} / year:")
    doc.add_paragraph(f"Purchaser: ${data['local_purchaser_amount']} | Days: {data['local_purchaser_days']}")
    doc.add_paragraph(f"Vendor: ${data['local_vendor_amount']} | Days: {data['local_vendor_days']}")
    doc.add_paragraph(f"Installment Paid? {data['local_installment_paid']}")

    # Regional Council Breakdown
    doc.add_paragraph(f"\n{data['regional_council']} Rates Calculation @ ${data['regional_yearly_rates']} / year:")
    doc.add_paragraph(f"Purchaser: ${data['regional_purchaser_amount']} | Days: {data['regional_purchaser_days']}")
    doc.add_paragraph(f"Vendor: ${data['regional_vendor_amount']} | Days: {data['regional_vendor_days']}")
    doc.add_paragraph(f"Installment Paid? {data['regional_installment_paid']}")

    # Convert document to bytes
    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer.getvalue()
